spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    hikari:
      username:  ${POSTGRES_USER}
      password: ${POSTGRES_PASS}
      driver-class-name: org.postgresql.Driver

logging:
  level:
    root: info
    sql: debug