spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    hikari:
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASS}
      driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
rabbitmq:
  queue1: my_test_queue1
  queue2: my_test_queue2
  exchange: my_test_exchange
  routingkey1: my_test_routingkey1
  routingkey2: my_test_routingkey2

logging:
  level:
    root: info
    sql: debug